name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "STAGING_DB_ADDRESS=${{ secrets.STAGING_DB_ADDRESS }}" > .env
          echo "STAGING_DB_PORT=${{ secrets.STAGING_DB_PORT }}" >> .env
          echo "STAGING_DB_NAME=${{ secrets.STAGING_DB_NAME }}" >> .env

      - name: Build Docker image
        run: |
          docker build --tag maxlebic1/ensae_infra_api:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push maxlebic1/ensae_infra_api:latest
